name: Compilar Aplicación para Windows y Mac

on: [push]

jobs:
  build-apps:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
<<<<<<< Updated upstream
    
=======

    # Le decimos en qué "cocina" trabajar
>>>>>>> Stashed changes
    runs-on: ${{ matrix.os }}

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar reportlab pillow pymupdf

<<<<<<< Updated upstream
      - name: Compilar App (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "BarbateCFApp" ^
          --add-data "data;data" ^
          --add-data "icons;icons" ^
          --add-data "club_logo.png;." ^
          --add-data "player_red_base.png;." ^
          --add-data "player_yellow_base.png;." ^
          --add-data "arialbd.ttf;." ^
          --add-data "logo.ico;." ^
          main.py
      
      - name: Compilar App (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "BarbateCFApp" \
          --add-data "data:data" \
          --add-data "icons:icons" \
          --add-data "club_logo.png:." \
          --add-data "player_red_base.png:." \
          --add-data "player_yellow_base.png:." \
          --add-data "arialbd.ttf:." \
          --add-data "logo.ico:." \
          main.py
=======
      # 4. Compilar la aplicación usando el archivo .spec
      - name: Compilar con PyInstaller
        # --- CORRECCIÓN: Añadido --noconfirm y --clean ---
        run: pyinstaller --noconfirm --clean BarbateCFApp.spec
>>>>>>> Stashed changes

      - name: Subir artefacto (Windows)
<<<<<<< Updated upstream
        if: matrix.os == 'windows-latest'
=======
        if: runner.os == 'Windows'
>>>>>>> Stashed changes
        uses: actions/upload-artifact@v4
        with:
          name: BarbateCFApp-Windows
          path: dist/BarbateCFApp.exe

      - name: Subir artefacto (macOS)
<<<<<<< Updated upstream
        if: matrix.os == 'macOS'
=======
        if: runner.os == 'macOS'
>>>>>>> Stashed changes
        uses: actions/upload-artifact@v4
        with:
          name: BarbateCFApp-macOS
          path: dist/BarbateCFApp.app