name: Compilar Aplicación para Windows y Mac

on: [push]

jobs:
  build-apps:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar reportlab pillow pymupdf

      - name: Compilar con PyInstaller
        run: pyinstaller --noconfirm --clean BarbateCFApp.spec

      - name: Subir artefacto (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: BarbateCFApp-Windows
          path: dist/BarbateCFApp.exe

      - name: Subir artefacto (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: BarbateCFApp-macOS
          path: dist/BarbateCFApp.app